kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-adm2021
  name: pinot
  annotations:
    dashboard.garden.sapcloud.io/no-hibernation-schedule: 'true'
spec:
  provider:
    type: gcp
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.250.0.0/16
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-c
    workers:
    - name: worker-vl1uq
      minimum: 1
      maximum: 3
      maxSurge: 1
      machine:
        type: n1-standard-4
        image:
          name: gardenlinux
          version: 184.0.0
      zones:
      - europe-west1-c
      volume:
        type: pd-ssd
        size: 50Gi
  networking:
    nodes: 10.250.0.0/16
    type: calico
  cloudProfileName: gcp
  region: europe-west1
  secretBindingName: secret-gcp
  kubernetes:
    version: 1.20.2
  purpose: development
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: true
  maintenance:
    timeWindow:
      begin: 030000+0100
      end: 040000+0100
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  hibernation:
    schedules: []
