{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: pinot-basic-auth
  namespace: {{ .Release.Namespace }}
data:
  auth: {{ .Values.ingress.basicAuth | b64enc | quote }}
{{- end }}
