{{- if .Values.ingress.enabled -}}
  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
  {{- else }}
apiVersion: networking.k8s.io/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: pinot
  {{- if .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: pinot-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - adm-pinot'
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
      - path: /
        {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: pinot-controller
            port:
              number: 9000
        {{- else }}
        backend:
          serviceName: pinot-controller
          servicePort: 9000
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- .Values.ingress.tls | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  {{- end }}
