jupyterhub:
  proxy:
    service:
      type: ClusterIP # disable LoadBalancer, we'll use an Ingress

  singleuser:
    defaultUrl: "/lab" # switch to new UI
    image:
      name: ghcr.io/timebertt/adm-pinot/jupyter-pinot
      tag: 0ca1fcc267da3a3d7e9507baf2421a5d9459a467

  hub:
    config:
      GitHubOAuthenticator:
        # configures these values in values.secret.yaml
        # client_id: <client-id>
        # client_secret: <client-secret>
        oauth_callback_url: https://jupyter.ingress.pinot.adm2021.shoot.canary.k8s-hana.ondemand.com/hub/oauth_callback
        allowed_users:
        - timebertt
        - nikolacornelia
#        - pfisterer
        scope:
        - read:user
      JupyterHub:
        authenticator_class: github
      Authenticator:
        auto_login: true
        admin_users:
        - timebertt
        - nikolacornelia

  ingress:
    enabled: true
    annotations:
      cert.gardener.cloud/purpose: managed
    tls:
    - hosts:
      - jupyter.ingress.pinot.adm2021.shoot.canary.k8s-hana.ondemand.com
      secretName: jupyter-tls
    hosts:
    - jupyter.ingress.pinot.adm2021.shoot.canary.k8s-hana.ondemand.com
