pinot:
  image:
    repository: apachepinot/pinot
    tag: 0.6.0
  cluster:
    name: pinot
  controller:
    external:
      type: ClusterIP
    persistence:
      size: 10Gi
  broker:
    external:
      type: ClusterIP
  server:
    replicaCount: 3
    persistence:
      size: 10Gi
  minion:
    # workaround for https://github.com/apache/incubator-pinot/issues/6704
    dataDir: /var/pinot/minion/data/data
    persistence:
      size: 10Gi

  zookeeper:
    persistence:
      size: 10Gi

ingress:
  enabled: false
  #  annotations: {}
  #  tls:
  #  - hosts:
  #    - pinot.example.com
  #    secretName: pinot-tls
  #  hosts:
  #  - pinot.example.com

kafka:
  nameOverride: kafka

  deleteTopicEnable: true

  logRetentionHours: 720 # 30 days

  zookeeper:
    nameOverride: kafka-zookeeper

storageClass:
  create: false
  name: pd-ssd
  type: pd-ssd
  provisioner: pd.csi.storage.gke.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
