pinot:
  image:
    repository: apachepinot/pinot
    tag: 0.6.0
  cluster:
    name: pinot
  controller:
    external:
      type: ClusterIP
    persistence:
      storageClass: pd-ssd
      size: 10Gi
  broker:
    external:
      type: ClusterIP
  server:
    replicaCount: 3
    persistence:
      storageClass: pd-ssd
      size: 10Gi
  minion:
    # workaround for https://github.com/apache/incubator-pinot/issues/6704
    dataDir: /var/pinot/minion/data/data
    persistence:
      storageClass: pd-ssd
      size: 10Gi

  zookeeper:
    persistence:
      storageClass: pd-ssd
      size: 10Gi

examples:
  enabled: false

ingress:
  enabled: true
  annotations:
    cert.gardener.cloud/purpose: managed
  tls:
  - hosts:
    - pinot.ingress.pinot.adm2021.shoot.canary.k8s-hana.ondemand.com
    secretName: pinot-tls
  hosts:
  - pinot.ingress.pinot.adm2021.shoot.canary.k8s-hana.ondemand.com

kafka:
  nameOverride: kafka

  persistence:
    storageClass: pd-ssd

  deleteTopicEnable: true

  logRetentionHours: 720 # 30 days

  zookeeper:
    nameOverride: kafka-zookeeper
    persistence:
      storageClass: pd-ssd

storageClass:
  create: true
  name: pd-ssd
  type: pd-ssd
  provisioner: pd.csi.storage.gke.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
