image:
  tag: 1.0.1

additionalRequirements:
- "psycopg2==2.8.5"
- "redis==3.2.1"
- "pinotdb==0.3.3"

extraConfigs:
  datasources-init.yaml: |
    databases:
    - database_name: pinot-github-events
      sqlalchemy_uri: pinot+http://pinot-broker:8099/query?server=http://pinot-controller:9000/
      tables:
      - table_name: pullRequestMergedEvents
        metrics:
        - expression: sum(count)
          metric_name: pr_count
          metric_type: count
          verbose_name: sum(count)
        columns:
        - column_name: mergedTimeMillis
          is_dttm: true
          python_date_format: epoch_ms
          type: LONG
        - column_name: ArrDel15
          type: LONG
        - column_name: title
          type: STRING
        - column_name: labels
          type: STRING
        - column_name: userId
          type: STRING
        - column_name: userType
          type: STRING
        - column_name: authorAssociation
          type: STRING
        - column_name: mergedBy
          type: STRING
        - column_name: assignees
          type: STRING
        - column_name: authors
          type: STRING
        - column_name: committers
          type: STRING
        - column_name: requestedReviewers
          type: STRING
        - column_name: requestedTeams
          type: STRING
        - column_name: reviewers
          type: STRING
        - column_name: commenters
          type: STRING
        - column_name: repo
          type: STRING
        - column_name: organization
          type: STRING
        - column_name: count
          type: LONG
        - column_name: numComments
          type: LONG
        - column_name: numReviewComments
          type: LONG
        - column_name: numCommits
          type: LONG
        - column_name: numLinesAdded
          type: LONG
        - column_name: numLinesDeleted
          type: LONG
        - column_name: numFilesChanged
          type: LONG
        - column_name: numAuthors
          type: LONG
        - column_name: numCommitters
          type: LONG
        - column_name: numReviewers
          type: LONG
        - column_name: numCommenters
          type: LONG
        - column_name: createdTimeMillis
          type: LONG
        - column_name: elapsedTimeMillis
          type: LONG

postgresql:
  persistence:
    storageClass: pd-ssd
